### ISSUE TITLE
[Odoo8] Javascript never gets called

### ISSUE THREAD

**Issue by SVQTQ** [messakali/sysmart_odoo_addons#1]
Hello

I have installed the module form_edit_mode on an odoo8-server.
The installation runs as it should, but when I return a view with target 'current_edit' the js file you supplied never gets called.
I tried a 'console.log' in the init-function but with no luck.
Was this originally written for the odoo7 or am I missing something here?

**Comment by messakali** [comment]
Hello,
Yes it was written and tested for odoo7

**Comment by SVQTQ** [comment]
Hello

In odoo8 this module is somewhat redundant indeed. I did not know this until I read a post on the odoo mailing list.

To do so, when returning a dictionary with type ir.ui.view you can pass the key 'flags' with a dictionary with key 'initial_mode' and value 'edit'

Thanks for responding, by the way.

Sent from Outlook Mobilehttps://aka.ms/blhgte

On Fri, Jan 22, 2016 at 12:02 PM -0800, "Mohamed Essakali" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello,
Yes it was written and tested for odoo7

##
